name: CI - Timberland bot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Lint (optional)
        run: |
          python -m pip install flake8
          flake8 --max-line-length=120 || true

      - name: Dry run playwright scraper
        run: |
          python main_playwright.py --dry-run || python main_playwright.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

      - name: Bot import sanity
        run: |
          python - << 'PY'
          import importlib.util
          spec = importlib.util.spec_from_file_location("bot","main_bot.py")
          m = importlib.util.module_from_spec(spec)
          spec.loader.exec_module(m)
          print("main_bot imported OK")
          PY
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
